#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '1.8.4'

cookbook 'java', '1.9.2'

cookbook 'build-essential', '1.3.4'

cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'

# Personal cookbooks go here
cookbook 'whoward-personal', :path => "vendor/whoward-personal"